<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>
<ItemGroup>
<ProjectReference Include="../Company.Tibco.Adb.Abstractions/Company.Tibco.Adb.Abstractions.csproj" />
</ItemGroup>
<ItemGroup>
  <Reference Include="Company.Tibco.Amps.Abstractions">
    <HintPath>..\..\01-AMPS\Company.Tibco.Amps.Abstractions\bin\Release\net8.0\Company.Tibco.Amps.Abstractions.dll</HintPath>
  </Reference>
</ItemGroup>
</Project>
