<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Company.Tibco.Adb</PackageId>
		<Version>1.0.0</Version>
		<PackageOutputPath>..\..\02-ADB\NuggetPackages</PackageOutputPath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Company.Tibco.Adb.Abstractions\Company.Tibco.Adb.Abstractions.csproj" />
		<ProjectReference Include="..\Company.Tibco.Adb.Core\Company.Tibco.Adb.Core.csproj" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.20" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="Company.Tibco.Amps.Abstractions">
	    <HintPath>..\..\01-AMPS\Company.Tibco.Amps.Abstractions\bin\Release\net8.0\Company.Tibco.Amps.Abstractions.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
