<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="..\Company.Tibco.Amps.Abstractions\Company.Tibco.Amps.Abstractions.csproj"/><ProjectReference Include="..\Company.Tibco.Amps.Client\Company.Tibco.Amps.Client.csproj"/><ProjectReference Include="..\Company.Tibco.Amps.DependencyInjection\Company.Tibco.Amps.DependencyInjection.csproj"/><FrameworkReference Include="Microsoft.AspNetCore.App"/></ItemGroup></Project>
