<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OutboundWorker-2d0c5b1b-6b14-441e-9592-96809f3670cb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AMPS.Client" Version="5.3.5.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedContracts\SharedContracts.csproj" />
  </ItemGroup>
</Project>
