<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="..\Company.Tibco.Adb.Database\Company.Tibco.Adb.Database.csproj"/><ProjectReference Include="..\Company.Tibco.Adb.DependencyInjection\Company.Tibco.Adb.DependencyInjection.csproj"/></ItemGroup></Project>
