<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Company.Tibco.Adb.Abstractions\Company.Tibco.Adb.Abstractions.csproj" />
		<ProjectReference Include="..\Company.Tibco.Adb.Database\Company.Tibco.Adb.Database.csproj" />
		<ProjectReference Include="..\..\01-AMPS\Company.Tibco.Amps.DependencyInjection\Company.Tibco.Amps.DependencyInjection.csproj" />
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
