<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-InboundWorker-d6534375-4122-450a-87ee-963d214e4965</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AMPS.Client" Version="5.3.5.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OutboundWorker\OutboundWorker.csproj" />
    <ProjectReference Include="..\SharedContracts\SharedContracts.csproj" />
  </ItemGroup>
</Project>
